import { useState, useEffect } from 'react';
import {
  fetchReports,
  generateMonthlyReport,
  generateQuarterlyReport,
  generateAnnualReport,
  generateCustomReport,
  deleteReport,
} from '../api/reports';
import { fetchDashboardSummary } from '../api/dashboard';
import AppLayout from '../components/AppLayout';
import './Reports.css';

function formatCurrency(value) {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    minimumFractionDigits: 0,
  }).format(value);
}

function formatDate(dateStr) {
  return new Date(dateStr).toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  });
}

const REPORT_CARDS = [
  {
    type: 'monthly',
    title: 'Monthly Report',
    icon: '📅',
    desc: 'Complete monthly financial summary with all transactions and insights',
  },
  {
    type: 'quarterly',
    title: 'Quarterly Report',
    icon: '📊',
    desc: 'Comprehensive quarterly analysis with trends and projections',
  },
  {
    type: 'annual',
    title: 'Annual Report',
    icon: '📈',
    desc: 'Full year financial overview with tax implications and investment analysis',
  },
  {
    type: 'custom',
    title: 'Custom Report',
    icon: '🎯',
    desc: 'Tailored report with specific date ranges and categories',
  },
];

export default function Reports() {
  const [reports, setReports] = useState([]);
  const [summary, setSummary] = useState(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState('');
  const [deletingId, setDeletingId] = useState(null);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');

  // Custom date modal
  const [showCustomModal, setShowCustomModal] = useState(false);
  const [customStart, setCustomStart] = useState('');
  const [customEnd, setCustomEnd] = useState('');

  const userRole = localStorage.getItem('user_role') || 'VIEWER';
  const isAdmin = userRole === 'ADMIN';

  useEffect(() => {
    loadData();
  }, []);

  async function loadData() {
    setLoading(true);
    try {
      const [reps, sum] = await Promise.all([
        fetchReports(),
        fetchDashboardSummary(),
      ]);
      setReports(reps);
      setSummary(sum);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }

  async function handleGenerate(type) {
    setError('');
    setSuccess('');

    if (type === 'custom') {
      setShowCustomModal(true);
      return;
    }

    setGenerating(type);
    try {
      const generators = {
        monthly: generateMonthlyReport,
        quarterly: generateQuarterlyReport,
        annual: generateAnnualReport,
      };
      await generators[type]();
      setSuccess(`${type.charAt(0).toUpperCase() + type.slice(1)} report generated successfully!`);
      await loadData();
      setTimeout(() => setSuccess(''), 4000);
    } catch (err) {
      setError(err.message);
    } finally {
      setGenerating('');
    }
  }

  async function handleGenerateCustom() {
    if (!customStart || !customEnd) {
      setError('Please select both start and end dates.');
      return;
    }
    setShowCustomModal(false);
    setGenerating('custom');
    setError('');
    setSuccess('');
    try {
      await generateCustomReport(customStart, customEnd);
      setSuccess('Custom report generated successfully!');
      setCustomStart('');
      setCustomEnd('');
      await loadData();
      setTimeout(() => setSuccess(''), 4000);
    } catch (err) {
      setError(err.message);
    } finally {
      setGenerating('');
    }
  }

  async function handleDelete(id) {
    if (!window.confirm('Delete this report?')) return;
    setDeletingId(id);
    try {
      await deleteReport(id);
      await loadData();
    } catch (err) {
      setError(err.message);
    } finally {
      setDeletingId(null);
    }
  }

  function handleDownload(report) {
    // Generate a simple text-based report for download
    const content = [
      `── ${report.name} ──`,
      ``,
      `Generated: ${formatDate(report.generatedDate)}`,
      `Period: ${formatDate(report.periodStart)} – ${formatDate(report.periodEnd)}`,
      `Type: ${report.reportType}`,
      ``,
      `── Financial Summary ──`,
      `Total Income:    ${formatCurrency(report.totalIncome)}`,
      `Total Expenses:  ${formatCurrency(report.totalExpense)}`,
      `Net Balance:     ${formatCurrency(report.balance)}`,
      `Transactions:    ${report.transactionCount}`,
      `Growth:          ${report.growthPercent >= 0 ? '+' : ''}${report.growthPercent}%`,
      ``,
      `── Generated by Finance Hub ──`,
    ].join('\n');

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${report.name.replace(/\s+/g, '_')}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  }

  // Calculate transaction count from reports or default to 0
  const totalTransactions = reports.reduce((sum, r) => sum + (r.transactionCount || 0), 0);
  const latestGrowth = reports.length > 0 ? (reports[0].growthPercent || 0) : 0;

  return (
    <AppLayout title="Financial Reports">
      {/* ─── Summary Strip ─── */}
      {summary && (
        <div className="reports-summary-strip">
          <div className="reports-stat">
            <span className="reports-stat-label">Total Balance</span>
            <span className="reports-stat-value">{formatCurrency(summary.balance)}</span>
          </div>
          <div className="reports-stat">
            <span className="reports-stat-label">Growth</span>
            <span className={`reports-stat-value ${latestGrowth >= 0 ? 'growth-positive' : 'growth-negative'}`}>
              {latestGrowth >= 0 ? '+' : ''}{latestGrowth}%
            </span>
          </div>
          <div className="reports-stat">
            <span className="reports-stat-label">Transactions</span>
            <span className="reports-stat-value">{totalTransactions}</span>
          </div>
        </div>
      )}

      {/* ─── Alerts ─── */}
      {success && <div className="reports-alert success">{success}</div>}
      {error && <div className="reports-alert error">{error}</div>}

      {/* ─── Report Cards Section ─── */}
      <div className="reports-section-header">
        <h2 className="reports-section-title">Financial Reports</h2>
      </div>

      <div className="report-cards-grid">
        {REPORT_CARDS.map((card) => (
          <div className="report-card" key={card.type}>
            <div className={`report-card-icon ${card.type}`}>{card.icon}</div>
            <h3 className="report-card-title">{card.title}</h3>
            <p className="report-card-desc">{card.desc}</p>
            <button
              className="btn-generate-card"
              onClick={() => handleGenerate(card.type)}
              disabled={!!generating}
              id={`generate-${card.type}-btn`}
            >
              {generating === card.type ? (
                <><span className="spinner" style={{ width: 14, height: 14, borderWidth: 2, borderTopColor: '#fff', borderColor: 'rgba(255,255,255,0.3)' }} /> Generating...</>
              ) : (
                'Generate'
              )}
            </button>
          </div>
        ))}
      </div>

      {/* ─── Custom Date Modal ─── */}
      {showCustomModal && (
        <div className="custom-date-modal-overlay" onClick={() => setShowCustomModal(false)}>
          <div className="custom-date-modal" onClick={(e) => e.stopPropagation()}>
            <h3>🎯 Custom Report</h3>
            <div className="custom-date-group">
              <label htmlFor="custom-start-date">Start Date</label>
              <input
                type="date"
                id="custom-start-date"
                value={customStart}
                onChange={(e) => setCustomStart(e.target.value)}
              />
            </div>
            <div className="custom-date-group">
              <label htmlFor="custom-end-date">End Date</label>
              <input
                type="date"
                id="custom-end-date"
                value={customEnd}
                onChange={(e) => setCustomEnd(e.target.value)}
              />
            </div>
            <div className="custom-date-actions">
              <button className="btn-primary-sm" onClick={handleGenerateCustom} id="confirm-custom-report-btn">
                Generate Report
              </button>
              <button className="btn-cancel-sm" onClick={() => setShowCustomModal(false)}>
                Cancel
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ─── Recent Reports ─── */}
      <div className="recent-reports-card">
        <h2>Recent Reports</h2>

        {loading ? (
          <div className="dashboard-loading">
            <div className="spinner-lg" />
            <span>Loading reports...</span>
          </div>
        ) : reports.length === 0 ? (
          <div className="reports-empty">
            <div className="reports-empty-icon">📋</div>
            <h3>No reports yet</h3>
            <p>Generate your first report using the cards above!</p>
          </div>
        ) : (
          reports.map((report) => (
            <div className="report-list-item" key={report.id}>
              <div className="report-list-info">
                <div className="report-list-name">{report.name}</div>
                <div className="report-list-date">{formatDate(report.generatedDate)}</div>
                <span className={`report-type-badge ${report.reportType.toLowerCase()}`}>
                  {report.reportType}
                </span>
                <div className="report-details-row">
                  <span className="report-detail-chip">
                    💰 {formatCurrency(report.totalIncome)}
                  </span>
                  <span className="report-detail-chip">
                    💸 {formatCurrency(report.totalExpense)}
                  </span>
                  <span className="report-detail-chip">
                    📊 Balance: {formatCurrency(report.balance)}
                  </span>
                  <span className="report-detail-chip">
                    🔢 {report.transactionCount} txns
                  </span>
                </div>
              </div>
              <div className="report-list-actions">
                <button
                  className="btn-download-report"
                  onClick={() => handleDownload(report)}
                  id={`download-report-${report.id}`}
                >
                  ⬇ Download
                </button>
                {isAdmin && (
                  <button
                    className="btn-delete-report"
                    onClick={() => handleDelete(report.id)}
                    disabled={deletingId === report.id}
                    id={`delete-report-${report.id}`}
                  >
                    {deletingId === report.id ? '...' : '🗑 Delete'}
                  </button>
                )}
              </div>
            </div>
          ))
        )}
      </div>
    </AppLayout>
  );
}
